# Generated by Django 5.0.6 on 2024-06-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        ('users', '0002_customuser_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tickets',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tickets',
            field=models.ManyToManyField(blank=True, null=True, to='tickets.tickets'),
        ),
    ]
