# Generated by Django 5.0.6 on 2024-06-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        ('users', '0003_remove_customuser_tickets_customuser_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='tickets.tickets'),
        ),
    ]
