# Generated by Django 5.0.6 on 2024-06-09 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tickets',
        ),
    ]
