# Generated by Django 5.0.6 on 2024-06-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_usertickets'),
        ('users', '0005_remove_customuser_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tickets',
            field=models.ManyToManyField(blank=True, through='tickets.UserTickets', to='tickets.tickets'),
        ),
    ]
