# Generated by Django 5.0.6 on 2024-06-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_locations_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='state',
            field=models.CharField(default='DE', max_length=100),
        ),
        migrations.AddField(
            model_name='locations',
            name='zip_code',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
