# Generated by Django 5.0.6 on 2024-06-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_ticket_usertickets_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertickets',
            old_name='tickets',
            new_name='ticket',
        ),
    ]
