# Generated by Django 5.0.6 on 2024-06-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_locations_city_locations_state_locations_zip_code'),
        ('tickets', '0005_rename_tickets_usertickets_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='locations.locations', blank=True, null=True),
        ),
    ]
